name        : polkit
version     : 0.113
release     : 11
source      :
    - https://www.freedesktop.org/software/polkit/releases/polkit-0.113.tar.gz : e1c095093c654951f78f8618d427faf91cf62abdefed98de40ff65eca6413c81
    - http://duktape.org/duktape-2.2.0.tar.xz : 62f72206427633077cb02e7ccd2599ace4d254db409334593b86d262c0d50c14
homepage    : http://www.freedesktop.org/wiki/Software/polkit
license     :
    - GPL-2.0
summary     : Application-level authorization toolkit
component   : system.base
description : |
    polkit is an application-level toolkit for defining and handling the policy that allows unprivileged processes to speak to privileged processes: It is a framework for centralizing the decision making process with respect to granting access to privileged operations for unprivileged applications. See the polkit(8) manual page for more detailed information.
builddeps  :
    - docbook-xml
    - pkgconfig(gtk-doc)
setup      : |
    # Patch the tree to be usable.
    %apply_patches
    
    # Prep duktake
    mkdir duktape
    tar xf $sources/duktape-2.2.0.tar.xz -C duktape --strip-components=1

    # Configure duktape
    pushd duktape
    python2 tools/configure.py --output-directory distrib-duktape \
        -UDUK_USE_ES6_PROXY \
        -UDUK_USE_DEBUG
    popd

    # Until we port to duktape 2:
    install -m 00644 duktape/extras/duk-v1-compat/{duk_v1_compat.c,duk_v1_compat.h} src/polkitbackend/.

    # Install the duktape build into our tree
    install -m 00644 duktape/distrib-duktape/{duk_config.h,duktape.c,duktape.h} src/polkitbackend/.
    %reconfigure --disable-static \
                 --libexecdir=%libdir%/polkit-1 \
                 --with-os-type=Solus \
                 --enable-libsystemd-login=yes \
                 --enable-introspection=yes \
                 --enable-gtk-doc \
                 --enable-gtk-doc-html
build      : |
    %make
install    : |
    %make_install

    # systemd can hook up users + stuff for us.
    install -D -m 00644 $pkgfiles/polkit.sysusers $installdir/%libdir%/sysusers.d/polkit.conf
    install -D -m 00644 $pkgfiles/polkit.tmpfiles $installdir/%libdir%/tmpfiles.d/polkit.conf

    # Make pam work goodly.
    install -m 00644 $pkgfiles/pam.d/polkit-1 $installdir/etc/pam.d/polkit-1
