name       : polkit
version    : 0.113
release    : 23
source     :
    - git|https://github.com/ikeydoherty/polkit-no-script.git : 5bcb1c1f9f678d950c44eccba81db36fddb09efc
homepage   : http://www.freedesktop.org/wiki/Software/polkit
license    :
    - GPL-2.0-or-later
summary    : Application-level authorization toolkit
component  :
    - system.base
    - devel : system.devel
description: |
    polkit is an application-level toolkit for defining and handling the policy that allows unprivileged processes to speak to privileged processes: It is a framework for centralizing the decision making process with respect to granting access to privileged operations for unprivileged applications. See the polkit(8) manual page for more detailed information.
builddeps  :
    - docbook-xml
    - pkgconfig(expat)
    - pkgconfig(gtk-doc)
    - pkgconfig(udev)
setup      : |
    # Patch the tree to be usable.
    %apply_patches

    export NOCONFIGURE=1

    %autogen --disable-static \
             --libexecdir=%libdir%/polkit-1 \
             --with-os-type=Solus \
             --enable-libsystemd-login=yes \
             --enable-introspection=yes \
             --enable-gtk-doc \
             --enable-gtk-doc-html \
             --with-wheel-group=sudo \
             --with-backend=keyfile \
             --disable-test
    # TODO: Make test suite work again!
build      : |
    %make
install    : |
    %make_install

    # systemd can hook up users + stuff for us.
    install -D -m 00644 $pkgfiles/polkit.sysusers $installdir/%libdir%/sysusers.d/polkit.conf
    install -D -m 00644 $pkgfiles/polkit.tmpfiles $installdir/%libdir%/tmpfiles.d/polkit.conf

    # Make pam work goodly.
    rm -rf $installdir/etc/pam.d
    install -Dm00644 $pkgfiles/pam.d/polkit-1 $installdir/usr/share/defaults/etc/pam.d/polkit-1
