name        : polkit
version     : 0.113
release     : 16
source      :
    - git|https://github.com/ikeydoherty/polkit-no-script.git : 551bc4b0e14bfb26d3a4341bedb8abe9cef570be
homepage    : http://www.freedesktop.org/wiki/Software/polkit
license     :
    - GPL-2.0
summary     : Application-level authorization toolkit
component   : system.base
description : |
    polkit is an application-level toolkit for defining and handling the policy that allows unprivileged processes to speak to privileged processes: It is a framework for centralizing the decision making process with respect to granting access to privileged operations for unprivileged applications. See the polkit(8) manual page for more detailed information.
builddeps  :
    - docbook-xml
    - pkgconfig(gtk-doc)
setup      : |
    # Patch the tree to be usable.
    %apply_patches

    export NOCONFIGURE=1

    %autogen --disable-static \
             --libexecdir=%libdir%/polkit-1 \
             --with-os-type=Solus \
             --enable-libsystemd-login=yes \
             --enable-introspection=yes \
             --enable-gtk-doc \
             --enable-gtk-doc-html \
             --with-wheel-group=sudo \
             --with-backend=keyfile \
             --disable-test
    # TODO: Make test suite work again!
build      : |
    %make
install    : |
    %make_install

    # systemd can hook up users + stuff for us.
    install -D -m 00644 $pkgfiles/polkit.sysusers $installdir/%libdir%/sysusers.d/polkit.conf
    install -D -m 00644 $pkgfiles/polkit.tmpfiles $installdir/%libdir%/tmpfiles.d/polkit.conf

    # Make pam work goodly.
    install -m 00644 $pkgfiles/pam.d/polkit-1 $installdir/etc/pam.d/polkit-1
