name       : polkit
version    : 121
release    : 26
source     :
    - https://www.freedesktop.org/software/polkit/releases/polkit-121.tar.gz : 9dc7ae341a797c994a5a36da21963f0c5c8e3e5a1780ccc2a5f52e7be01affaa
homepage   : http://www.freedesktop.org/wiki/Software/polkit
license    :
    - GPL-2.0-or-later
summary    : Application-level authorization toolkit
component  :
    - system.base
    - devel : system.devel
description: |
    polkit is an application-level toolkit for defining and handling the policy that allows unprivileged processes to speak to privileged processes: It is a framework for centralizing the decision making process with respect to granting access to privileged operations for unprivileged applications. See the polkit(8) manual page for more detailed information.
builddeps  :
    - docbook-xml
    - pkgconfig(duktape)
    - pkgconfig(expat)
    - pkgconfig(gtk-doc)
    - pkgconfig(udev)
    # check:
    - python-dbusmock
setup      : |
    # Patch the tree to be usable.
    %apply_patches

    %meson_configure -Dos_type=redhat \
                     -Dsession_tracking=libsystemd-login \
                     -Dexamples=true \
                     -Dman=true \
                     -Dgtk_doc=true \
                     -Dtests=true
build      : |
    %ninja_build
install    : |
    %ninja_install

    # systemd can hook up users + stuff for us.
    install -D -m 00644 $pkgfiles/polkit.sysusers $installdir/%libdir%/sysusers.d/polkit.conf
    install -D -m 00644 $pkgfiles/polkit.tmpfiles $installdir/%libdir%/tmpfiles.d/polkit.conf

    # Stateless
    rm -rf $installdir/etc/

    # Make pam work goodly
    install -Dm00644 $pkgfiles/pam.d/polkit-1 $installdir/usr/share/defaults/etc/pam.d/polkit-1
check      : |
    meson test -C solusBuildDir --print-errorlogs -t 3
